Repository honeycombio/libhoney-go, pull requests merged in 2022-01, with the labels that each got.

#156 fix: don't crash on stream aborts, always add content length
  transmission/transmission.go
  transmission/transmission_test.go
Labels: version: bump patch, merge at will

#157 Prepare v1.15.7 release
  CHANGELOG.md
  libhoney.go
Labels: type: maintenance, version: bump patch

#159 fix: pass bytes.Reader to http.Request, clean up pooledReader ourselves
  transmission/transmission.go
  transmission/transmission_test.go
Labels: version: bump patch, merge at will

#160 Prepare v1.15.8 release
  CHANGELOG.md
  libhoney.go
Labels: type: maintenance, version: bump patch

#162 Fix race condition in test and other test bugs
  transmission/transmission.go
  transmission/transmission_test.go
Labels: type: maintenance, version: no bump

#164 [go] drop support for go before 1.14
  .circleci/config.yml
  CHANGELOG.md
Labels: version: bump major
