Repository honeycombio/libhoney-go, pull requests merged in 2022-07, with the labels that each got.

#184 Update examples
  .circleci/config.yml
  examples/json_reader/example1.json
  examples/json_reader/example2.json
  examples/json_reader/read_json_log.go
  examples/webapp/Dockerfile
  examples/webapp/README.md
  examples/webapp/db.go
  examples/webapp/docker-compose.yml
  examples/webapp/go.mod
  examples/webapp/go.sum
  examples/webapp/handlers.go
  examples/webapp/honeycomb_helpers.go
  examples/webapp/main.go
  examples/webapp/templates/base.html
  examples/webapp/templates/home.html
  examples/webapp/templates/login.html
  examples/webapp/templates/signup.html
  examples/webapp/types.go
Labels: type: maintenance, version: no bump

#183 Add support to retrieve team and environment
  libhoney.go
  libhoney_test.go
Labels: type: enhancement, version: bump minor

#185 release: prep v2.2.0
  CHANGELOG.md
  libhoney.go
Labels: type: maintenance

#186 release: prepare v1.16.0
  CHANGELOG.md
  libhoney.go
Labels: type: maintenance
