Repository honeycombio/libhoney-go, pull requests merged in 2022-10, with the labels that each got.

#197 pre-define map capacities
  libhoney.go
Labels: status: oncall

#199 maint: add release file
  .github/release.yml
Labels: type: maintenance, version: no bump, merge at will, no-changelog

#205 maint: delete workflows for old board
  .github/workflows/add-to-project.yml
  .github/workflows/re-triage.yml
Labels: type: maintenance, version: no bump, merge at will

#207 feat: include Go version, GOOS, & GOARCH in user-agent
  .circleci/config.yml
  .gitignore
  Makefile
  RELEASING.md
  libhoney.go
  transmission/transmission.go
  transmission/transmission_test.go
  version/version.go
Labels: type: enhancement, version: bump minor

#208 release: prepare v1.18.0
  CHANGELOG.md
  version/version.go
Labels: type: maintenance, no-changelog
