Repository honeycombio/libhoney-go, pull requests merged in 2024-03, with the labels that each got.

#239 feat: introduce IsClassicKey helper function
  libhoney.go
Labels: type: enhancement

#240 rel: Prepare v1.22.0 release
  CHANGELOG.md
  version/version.go
Labels: type: maintenance, no-changelog

#241 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog
